# Back end & performance
use-damage = "false";
vsync = true;
backend = "glx";

# GLX settings
glx-no-stencil = true;
glx-copy-from-front = false;
glx-use-copysubbuffermesa = true;
glx-no-rebind-pixmap = false;
xrender-sync-fence = true;

# Opacity
active-opacity = 1;
inactive-opacity = 1;
frame-opacity = 1;
inactive-opacity-override = false;

# Intel tearing fix extras
unredir-if-possible = false;
